{"error":"報表匯出失敗","details":"❌ Python 執行錯誤：Command failed: /opt/anaconda3/envs/tf_env/bin/python /Users/yen/NCCU/大四（二）/DBMS/113-2-DBMS-Final-Project/scripts/excel_update.py {\"file_path\":\"/Users/yen/NCCU/大四（二）/DBMS/113-2-DBMS-Final-Project/server/scripts/ReportTemplate.xlsx\",\"output_path\":\"/Users/yen/NCCU/大四（二）/DBMS/113-2-DBMS-Final-Project/server/scripts/output.xlsx\",\"tasks\":[{\"sheet_name\":\"Social Interaction\",\"table_name\":\"Table3\",\"data\":[[\"\",\"\",\"\",\"\"]],\"metadata\":{\"Team\":\"èª²å¤æ´»åçµ\",\"Manager\":\"Yen\",\"Start Time\":\"2025-05-01\",\"End Time\":\"2025-05-21\"}},{\"sheet_name\":\"New SOP\",\"table_name\":\"Table1\",\"data\":[[\"\",\"\",\"\"]]},{\"sheet_name\":\"Update SOP\",\"table_name\":\"Table2\",\"data\":[[\"\",\"\",\"\",\"\",\"\",\"\"]]}]}\nTraceback (most recent call last):\n  File \"/Users/yen/NCCU/大四（二）/DBMS/113-2-DBMS-Final-Project/scripts/excel_update.py\", line 12, in <module>\n    wb = load_workbook(file_path)\n  File \"/opt/anaconda3/envs/tf_env/lib/python3.8/site-packages/openpyxl/reader/excel.py\", line 344, in load_workbook\n    reader = ExcelReader(filename, read_only, keep_vba,\n  File \"/opt/anaconda3/envs/tf_env/lib/python3.8/site-packages/openpyxl/reader/excel.py\", line 123, in __init__\n    self.archive = _validate_archive(fn)\n  File \"/opt/anaconda3/envs/tf_env/lib/python3.8/site-packages/openpyxl/reader/excel.py\", line 95, in _validate_archive\n    archive = ZipFile(filename, 'r')\n  File \"/opt/anaconda3/envs/tf_env/lib/python3.8/zipfile.py\", line 1253, in __init__\n    self.fp = io.open(file, filemode)\nFileNotFoundError: [Errno 2] No such file or directory: '/Users/yen/NCCU/大四（二）/DBMS/113-2-DBMS-Final-Project/server/scripts/ReportTemplate.xlsx'\n"}